{"uninstall": {"ipfs": false, "ipget": false, "cluster_follow": false}, "error": "Traceback (most recent call last):\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 2142, in test\n    results[\"install\"] = this_install_ipfs.install_and_configure()\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 2100, in install_and_configure\n    ipget = self.install_ipget()\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 723, in install_ipget\n    results = subprocess.check_output(command, shell=True)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\barberb\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\barberb\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command 'C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\binipget.exe --version' returned non-zero exit status 1.\nCommand 'C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\binipget.exe --version' returned non-zero exit status 1.2142"}