{"uninstall": {"ipfs": false, "ipget": false, "cluster_service": false, "cluster_ctl": false}, "error": "Traceback (most recent call last):\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 1243, in config_ipfs_cluster_service\n    elif platform.system() == \"Windows\":\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '/etc/systemd/system/ipfs-cluster.service'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 2587, in test\n    results = {}\n                 \n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 2557, in install_and_configure\n    pass\n         \n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 1251, in config_ipfs_cluster_service\n    enable_cluster_service_results = subprocess.check_output(enable_cluster_service, shell=True)\n    ^^^^^^^^^^^^^^^^^^^^^^^\nException: [Errno 2] No such file or directory: '/etc/systemd/system/ipfs-cluster.service'\n[Errno 2] No such file or directory: '/etc/systemd/system/ipfs-cluster.service'2587"}