{"uninstall": {"ipfs": false, "ipget": false, "cluster_follow": false}, "error": "Traceback (most recent call last):\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 2186, in test\n    results[\"install\"] = this_install_ipfs.install_and_configure()\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 2144, in install_and_configure\n    ipget = self.install_ipget()\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barberb\\ipfs_kit_py\\ipfs_kit_py\\install_ipfs.py\", line 754, in install_ipget\n    os.remove(os.path.join(self.this_dir, \"bin\", \"ipget.exe\"))\nPermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\\\Users\\\\barberb\\\\ipfs_kit_py\\\\ipfs_kit_py\\\\bin\\\\ipget.exe'\n[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\\\Users\\\\barberb\\\\ipfs_kit_py\\\\ipfs_kit_py\\\\bin\\\\ipget.exe'2186"}