{"uninstall": {"ipfs": true, "ipget": false, "cluster_service": false, "cluster_ctl": false}, "error": "Traceback (most recent call last):\n  File \"/home/barberb/ipfs_kit_py/ipfs_kit_py/install_ipfs.py\", line 3190, in test\n    results[\"install\"] = this_install_ipfs.install_and_configure()\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/barberb/ipfs_kit_py/ipfs_kit_py/install_ipfs.py\", line 3154, in install_and_configure\n    cluster_service_config = self.config_ipfs_cluster_service(\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/barberb/ipfs_kit_py/ipfs_kit_py/install_ipfs.py\", line 1437, in config_ipfs_cluster_service\n    if init_cluster_service_results == \"\":\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'init_cluster_service_results' where it is not associated with a value\ncannot access local variable 'init_cluster_service_results' where it is not associated with a value3190"}